-- 1
SELECT HOTEN,LUONG FROM GIAOVIEN 
WHERE PHAI = N'Nữ';
-- 2
SELECT HOTEN,LUONG*1.1 as LUONG FROM GIAOVIEN;
-- 3
SELECT MAGV FROM GIAOVIEN
WHERE HOTEN LIKE N'Nguyễn%' and LUONG>2000
UNION
SELECT  TRUONGBM  FROM BOMON
WHERE  year(NGAYNHANCHUC) >1995
-- 4
SELECT HOTEN
FROM GIAOVIEN,BOMON
WHERE GIAOVIEN.MABM = BOMON.MABM and BOMON.MAKHOA='CNTT';
-- 5
SELECT BM.*, GV.HOTEN, GV.LUONG,GV.PHAI,GV.NGAYSINH,GV.DIACHI,GV.GVQLCM
FROM BOMON BM,GIAOVIEN GV
WHERE GV.MAGV = BM.TRUONGBM
-- 6
SELECT GV.*,BM.TENBM, BM.PHONG, BM.DIENTHOAI, BM.TRUONGBM, BM.MAKHOA, BM.NGAYNHANCHUC
FROM GIAOVIEN GV, BOMON BM
WHERE GV.MABM = BM.MABM
-- 7
SELECT DT.TENDT, GV.*
FROM DETAI DT, GIAOVIEN GV
WHERE DT.GVCNDT=GV.MAGV
-- 8
SELECT KH.TENKHOA, GV.*
FROM KHOA KH, GIAOVIEN GV
WHERE KH.TRUONGKHOA=GV.MAGV
-- 9
SELECT GV.*
FROM  GIAOVIEN GV,BOMON BM, THAMGIADT TG
WHERE BM.TENBM=N'Vi sinh' and GV.MABM=BM.MABM 
and TG.MADT='006' and TG.MAGV = GV.MAGV; 
-- 10
SELECT MADT, TENCD,HOTEN,NGAYSINH,DIACHI
FROM DETAI,CHUDE,GIAOVIEN
WHERE DETAI.CAPQL=N'Nhà nước' and DETAI.MACD= CHUDE.MACD
and DETAI.GVCNDT=GIAOVIEN.MAGV
-- 11
SELECT GV1.HOTEN,GV2.HOTEN as GVQL
FROM GIAOVIEN GV1,GIAOVIEN GV2
WHERE GV1.GVQLCM = GV2.MAGV 
-- 12
SELECT GV1.HOTEN
FROM GIAOVIEN GV1,GIAOVIEN GV2
WHERE GV1.GVQLCM = GV2.MAGV and GV2.HOTEN=N'Nguyễn Thanh Tùng'

-- 13
SELECT HOTEN
FROM GIAOVIEN , BOMON
WHERE BOMON.TRUONGBM = GIAOVIEN.MAGV
and BOMON.TENBM=N'Hệ thống thông tin' 
-- 14
SELECT HOTEN
FROM DETAI,CHUDE,GIAOVIEN
WHERE CHUDE.TENCD=N'Quản lý giáo dục' and DETAI.MACD= CHUDE.MACD
and DETAI.GVCNDT=GIAOVIEN.MAGV
-- 15
SELECT TENCV
FROM DETAI,CONGVIEC
WHERE DETAI.TENDT=N'HTTT quản lý các trường ĐH' and DETAI.MADT= CONGVIEC.MADT
and YEAR(CONGVIEC.NGAYBD)=2008 and MONTH(CONGVIEC.NGAYBD)=3
-- 16
SELECT GV1.HOTEN,GV2.HOTEN as GVQLCM
FROM GIAOVIEN GV1,GIAOVIEN GV2
WHERE GV1.GVQLCM = GV2.MAGV 
-- 17
SELECT *
FROM CONGVIEC
WHERE NGAYBD BETWEEN  '01/01/2007' and '08/01/2007'
-- 18
SELECT GV.HOTEN
FROM  GIAOVIEN GV,BOMON BM, GIAOVIEN GV1
WHERE GV1.HOTEN=N'Trần Trà Hương' 
and GV.MABM =BM.MABM
and GV1.MABM=BM.MABM 
-- 19
SELECT DISTINCT GV.* 
FROM BOMON BM,DETAI DT, GIAOVIEN GV
WHERE BM.TRUONGBM=DT.GVCNDT and BM.TRUONGBM =GV.MAGV
and GV.MAGV=DT.GVCNDT
-- 20
SELECT DISTINCT GV.HOTEN
FROM BOMON BM,KHOA KH, GIAOVIEN GV
WHERE BM.TRUONGBM=KH.TRUONGKHOA and BM.TRUONGBM =GV.MAGV
and GV.MAGV=KH.TRUONGKHOA
-- 21
SELECT DISTINCT GV.HOTEN
FROM BOMON BM,DETAI DT, GIAOVIEN GV
WHERE BM.TRUONGBM=DT.GVCNDT and BM.TRUONGBM =GV.MAGV
and GV.MAGV=DT.GVCNDT
-- 22
SELECT DISTINCT GV.HOTEN
FROM KHOA KH,DETAI DT, GIAOVIEN GV
WHERE KH.TRUONGKHOA=DT.GVCNDT and KH.TRUONGKHOA =GV.MAGV
and GV.MAGV=DT.GVCNDT
-- 23
SELECT DISTINCT GV.MAGV
FROM  GIAOVIEN GV, THAMGIADT TG
WHERE GV.MABM='HTTT' or TG.MADT='001' 
and TG.MAGV = GV.MAGV
--24
SELECT DISTINCT GV.*
FROM  GIAOVIEN GV, GIAOVIEN GV1
WHERE GV1.MAGV='002' and GV.MABM = GV1.MABM
-- 25
SELECT GIAOVIEN.*
FROM GIAOVIEN , BOMON
WHERE GIAOVIEN.MAGV= BOMON.TRUONGBM 
-- 26
SELECT HOTEN,LUONG FROM GIAOVIEN 